apiVersion: v1
kind: Namespace
metadata:
  name: ${NS}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsplease-sa
  namespace: ${NS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nsplease-role
  namespace: ${NS}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nsplease-rb-self
  namespace: ${NS}
subjects:
  - kind: ServiceAccount
    name: nsplease-sa
    namespace: ${NS}
roleRef:
  kind: Role
  name: nsplease-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nsplease-rb-ci
  namespace: ${NS}
subjects:
  - kind: ServiceAccount
    name: nsplease-sa
    namespace: fabrique-ci
roleRef:
  kind: Role
  name: nsplease-role
  apiGroup: rbac.authorization.k8s.io
